/*
  ESTE ES EL ARCHIVO QUE EDITARAS NORMALMENTE.

  La web esta organizada en tres listas:
  1. BETTAS: bettas individuales.
  2. PAREJAS: parejas seleccionadas.
  3. ACCESORIOS: acuarios, filtros, betta stick, alimentacion, decoracion, etc.

  Fotos:
  - Guarda las imagenes dentro de la carpeta imagenes.
  - Usa el codigo del producto: HM002-1.jpg, HM002-2.jpeg, ACC001-1.png...
  - La web detecta automaticamente .jpg, .jpeg, .png, .webp y mayusculas.

  Videos:
  - Video local: guarda el archivo en videos y escribe videoLocal: "videos/HM002.mp4".
  - TikTok: pega el enlace en videoTikTok.
  - Si no hay video, deja videoLocal: "" y videoTikTok: "".

  Estados:
  - Bettas y parejas: "disponible" o "vendido".
  - Accesorios: "disponible" o "agotado".

  Precios:
  - Sin oferta: precioAnterior: null.
  - Con oferta: precioAnterior con el precio antiguo. El descuento se calcula solo.

  Orden:
  - orden: 1 aparece antes que orden: 2.
  - Puedes usar 1, 2, 3... o dejar huecos como 10, 20, 30.
  - Si dos productos tienen el mismo orden, se mantiene el orden escrito aqui.
  - Si un producto no tiene orden, aparece despues de los productos con orden.
*/

const CONFIGURACION = {
  // Formato: codigo de pais + numero, sin espacios ni simbolos.
  // Ejemplo de Espana: 34600111222
  whatsapp: "34603715888",

  // Redes sociales. Puedes cambiar estas direcciones cuando quieras.
  tiktok: "https://www.tiktok.com/@betta_tailandia_en_bcn",
  instagram: "https://www.instagram.com/bettabcn",
  facebook: "https://www.facebook.com/profile.php?id=61590687530711",
};
  //Vendido 4000
  //Vendido Pareja 4400
  //Pareja 1500
  //Acesorio 2000
  //Codigo Año+orden+mes+dia 

const BETTAS = [
  {
    codigo: "HM001",
    orden: 01,
    categoria: "betta",
    variedad: "Halfmoon Blue Metalic",
    estado: "disponible",
    sexo: "Macho",
    precio: 50,
    precioAnterior: null,
    descripcion: "",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "R26490830",
    orden: 49,
    categoria: "betta",
    variedad: "HMPK Super Black",
    estado: "disponible",
    sexo: "Macho",
    precio: 33,
    precioAnterior: 38,
    descripcion: "Macho Super Black ENVIO ALEATORIO",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "R26500830",
    orden: 50,
    categoria: "betta",
    variedad: "HMPK Super Red",
    estado: "disponible",
    sexo: "Macho",
    precio: 33,
    precioAnterior: 38,
    descripcion: "Macho Super Red ENVIO ALEATORIO",
    videoLocal: "videos/R26500830.mp4",
    videoTikTok: "",
  },
  {
    codigo: "KOI003",
    orden: 51,
    categoria: "betta",
    variedad: "HMPK Red Koi Galaxy",
    estado: "disponible",
    sexo: "Macho",
    precio: 45,
    precioAnterior: null,
    descripcion: "",
    videoLocal: "videos/KOI003.mp4",
    videoTikTok: "",
  },
  {
    codigo: "R26520830",
    orden: 52,
    categoria: "betta",
    variedad: "HMPK Red Black Candy Metalic",
    estado: "disponible",
    sexo: "Macho",
    precio: 45,
    precioAnterior: null,
    descripcion: "",
    videoLocal: "videos/R26520830.mp4",
    videoTikTok: "",
  },
  {
    codigo: "P26530830",
    orden: 53,
    categoria: "betta",
    variedad: "HMPK Pastel White",
    estado: "disponible",
    sexo: "Macho",
    precio: 35,
    precioAnterior: 40,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "P26540830",
    orden: 54,
    categoria: "betta",
    variedad: "HMPK Pineapple Metallic",
    estado: "disponible",
    sexo: "Macho",
    precio: 40,
    precioAnterior: null,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "R26550830",
    orden: 55,
    categoria: "betta",
    variedad: "HMPK Royal Blue Metallic",
    estado: "disponible",
    sexo: "Macho",
    precio: 48,
    precioAnterior: null,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "R26560830",
    orden: 56,
    categoria: "betta",
    variedad: "HMPK Blue & White",
    estado: "disponible",
    sexo: "Macho",
    precio: 30,
    precioAnterior: 40,
    descripcion: "OFERTA",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "W001",
    orden: 501,
    categoria: "betta",
    variedad: "Betta Splendens Wild Type Red – Spade Tail",
    estado: "disponible",
    sexo: "Macho",
    precio: 40,
    precioAnterior: null,
    descripcion: "",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "W002",
    orden: 500,
    categoria: "betta",
    variedad: "Betta Splendens Wild Type Red – Spade Tail",
    estado: "disponible",
    sexo: "Macho",
    precio: 42,
    precioAnterior: null,
    descripcion: "",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "G002",
    orden: 999,
    categoria: "betta",
    variedad: "HMPK Gigant Super Red",
    estado: "disponible",
    sexo: "Macho",
    precio: 50,
    precioAnterior: 60,
    descripcion: "Tamaño 6-7cm",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "G001",
    orden: 1000,
    categoria: "betta",
    variedad: "HMPK Gigant Nemo",
    estado: "disponible",
    sexo: "Macho",
    precio: 53,
    precioAnterior: 60,
    descripcion: "Tamaño 6.5-7.5cm",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "KOI001",
    orden: 1497,
    categoria: "betta",
    variedad: "KOI Metalico",
    estado: "disponible",
    sexo: "Macho",
    precio: 39,
    precioAnterior: 42,
    descripcion: "Blanco",
    videoLocal: "",
    videoTikTok: "https://vm.tiktok.com/ZNRcghhvK/",
  },
  {
    codigo: "KOI002",
    orden: 1498,
    categoria: "betta",
    variedad: "KOI Metalico",
    estado: "disponible",
    sexo: "Macho",
    precio: 38,
    precioAnterior: 42,
    descripcion: "Amarillo",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "HM002",
    orden: 1499,
    categoria: "betta",
    variedad: "Halfmoon",
    estado: "disponible",
    sexo: "Macho",
    precio: 40,
    precioAnterior: 45,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "",
  },
  //------------------------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------------------------
  //------------------------------------------------------------------------------------------------------------------------------------------------------------
  {
    codigo: "b4000",
    orden: 4000,
    categoria: "betta",
    variedad: "HMPK Blue Black Panda",
    estado: "vendido",
    sexo: "Macho",
    precio: 90,
    precioAnterior: null,
    descripcion: "Calidad A+",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "f4001",
    orden: 4001,
    categoria: "betta",
    variedad: "HMPK Fancy Avatar",
    estado: "vendido",
    sexo: "Macho",
    precio: 85,
    precioAnterior: null,
    descripcion: "Calidad A+",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "m4002",
    orden: 4002,
    categoria: "betta",
    variedad: "HMPK Multicolor Candy",
    estado: "vendido",
    sexo: "Macho",
    precio: 90,
    precioAnterior: null,
    descripcion: "Calidad A+",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "mcg4003",
    orden: 4003,
    categoria: "betta",
    variedad: "HMPK Multicolor Candy Galaxy",
    estado: "vendido",
    sexo: "Macho",
    precio: 120,
    precioAnterior: null,
    descripcion: "Calidad S",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "byc4004",
    orden: 4004,
    categoria: "betta",
    variedad: "HMPK Black Yellow Candy",
    estado: "vendido",
    sexo: "Macho",
    precio: 90,
    precioAnterior: null,
    descripcion: "Calidad A+",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "n4005",
    orden: 4005,
    categoria: "betta",
    variedad: "HMPK Nemo Candy Galaxy Multicolor",
    estado: "vendido",
    sexo: "Macho",
    precio: 145,
    precioAnterior: null,
    descripcion: "Calidad S+",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "HB001",
    orden: 4503,
    categoria: "betta",
    variedad: "Hell Boy",
    estado: "vendido",
    sexo: "Macho",
    precio: 39,
    precioAnterior: 45,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "https://vm.tiktok.com/ZNRc72upt/",
  },
  {
    codigo: "HB002",
    orden: 4502,
    categoria: "betta",
    variedad: "Hell Boy",
    estado: "vendido",
    sexo: "Macho",
    precio: 39,
    precioAnterior: 45,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "https://vm.tiktok.com/ZNRc72upt/",
  },
  {
    codigo: "CN001",
    orden: 4501,
    categoria: "betta",
    variedad: "Candy Metalico",
    estado: "vendido",
    sexo: "Macho",
    precio: 39,
    precioAnterior: 42,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "https://vm.tiktok.com/ZNRcWETmK/",
  },
  {
    codigo: "CT001",
    orden: 4500,
    categoria: "betta",
    variedad: "Crowntail",
    estado: "vendido",
    sexo: "Macho",
    precio: 38,
    precioAnterior: 45,
    descripcion: "Coloracion segun fotografias.",
    videoLocal: "",
    videoTikTok: "",
  },
];

const PAREJAS = [
  // Ejemplo para copiar cuando tengas una pareja:
  // {
  //   codigo: "PAR001",
  //   orden: 10,
  //   categoria: "pareja",
  //   variedad: "Pareja Hell Boy",
  //   estado: "disponible",
  //   sexo: "Macho + Hembra",
  //   precio: 75,
  //   precioAnterior: null,
  //   descripcion: "Pareja seleccionada para cria.",
  //   videoLocal: "videos/PAR001.mp4",
  //   videoTikTok: "",
  // },
  {
    codigo: "P2615000830",
    orden: 1500,
    categoria: "pareja",
    variedad: "Pareja Super Red",
    estado: "disponible",
    sexo: "Macho + Hembra",
    precio: 60,
    precioAnterior: 65,
    descripcion: "Pareja Super Red ENVIO ALEATORIO.",
    videoLocal: "videos/P2615000830.mp4",
    videoTikTok: "",
  },
  {
    codigo: "P2615010830",
    orden: 1501,
    categoria: "pareja",
    variedad: "Pareja Super Black",
    estado: "disponible",
    sexo: "Macho + Hembra",
    precio: 60,
    precioAnterior: 65,
    descripcion: "Pareja Super Black ENVIO ALEATORIO.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "P2615020830",
    orden: 1502,
    categoria: "pareja",
    variedad: "Pareja HMPK Pineapple",
    estado: "disponible",
    sexo: "Macho + Hembra",
    precio: 72,
    precioAnterior: 78,
    descripcion: "PAREJA SUPER RED ENVIO ALEATORIO.",
    videoLocal: "videos/P2615020830.mp4",
    videoTikTok: "",
  },
  {
    codigo: "24K4400",
    orden: 4400,
    categoria: "pareja",
    variedad: "HMPK 24K Gold",
    estado: "vendido",
    sexo: "Macho + Hembra",
    precio: 145,
    precioAnterior: null,
    descripcion: "Pareja 24K Gold Calidad A+. Perfecto para criar",
    videoLocal: "",
    videoTikTok: "",
  },
];

const ACCESORIOS = [
  {
    codigo: "AV001",
    orden: 2000,
    categoria: "accesorio",
    tipoAccesorio: "betta-stick",
    nombre: "Varita para betta",
    estado: "disponible",
    precio: 10,
    precioAnterior: null,
    descripcion: "Longitud total de 19cm aprox.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "AV002",
    orden: 2001,
    categoria: "accesorio",
    tipoAccesorio: "betta-stick",
    nombre: "Varita para betta roja",
    estado: "disponible",
    precio: 6,
    precioAnterior: null,
    descripcion: "Rojo.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "APack001",
    orden: 2002,
    categoria: "accesorio",
    tipoAccesorio: "acuario",
    nombre: "Acuario 20 x 20 x 25 kit completo",
    estado: "disponible",
    precio: 70,
    precioAnterior: null,
    descripcion: "Acuario 20cm x 20cm x 25cm + luz + filtro + arena negra + decoracion + red + tapa + sifon de limpieza.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "OTOHIME50A",
    orden: 2003,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 50G",
    estado: "disponible",
    precio: 5,
    precioAnterior: null,
    descripcion: "A - B1 - B2 - C. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "OTOHIME50S",
    orden: 2004,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 50G",
    estado: "disponible",
    precio: 4.25,
    precioAnterior: null,
    descripcion: "S1 - S2. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  }, 
  {
    codigo: "OTOHIME100A",
    orden: 2005,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 100G",
    estado: "disponible",
    precio: 8,
    precioAnterior: null,
    descripcion: "A - B1 - B2 - C. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "OTOHIME100S",
    orden: 2006,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 100G",
    estado: "disponible",
    precio: 7.5,
    precioAnterior: null,
    descripcion: "S1 - S2. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  }, 
  {
    codigo: "OTOHIME100E",
    orden: 2006,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 100G",
    estado: "disponible",
    precio: 7,
    precioAnterior: null,
    descripcion: "EP0 - EP1 - EP2 - EP3 - EP4. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  }, 
  {
    codigo: "OTOHIME500A",
    orden: 2007,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 500G",
    estado: "disponible",
    precio: 33.5,
    precioAnterior: null,
    descripcion: "A - B1 - B2 - C. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "OTOHIME500S",
    orden: 2008,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 500G",
    estado: "disponible",
    precio: 30,
    precioAnterior: null,
    descripcion: "S1 - S2. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  }, 
  {
    codigo: "OTOHIME500E",
    orden: 2009,
    categoria: "accesorio",
    tipoAccesorio: "Alimento para peces",
    nombre: "Alimento OTOHIME de 500G",
    estado: "disponible",
    precio: 27,
    precioAnterior: null,
    descripcion: "EP0 - EP1 - EP2 - EP3 - EP4. Entrega 14 dias (aprox.)",
    videoLocal: "",
    videoTikTok: "",
  }, 
  /*{
    codigo: "A202025F",
    orden: 23,
    categoria: "accesorio",
    tipoAccesorio: "acuario",
    nombre: "Acuario 20 x 20 x 25 + filtro",
    estado: "agotado",
    precio: 29,
    precioAnterior: null,
    descripcion: "Acuario 20cm x 20cm x 25cm + filtro de 5W.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "A202025",
    orden: 24,
    categoria: "accesorio",
    tipoAccesorio: "acuario",
    nombre: "Acuario 20 x 20 x 25",
    estado: "agotado",
    precio: 20,
    precioAnterior: null,
    descripcion: "Acuario 20cm x 20cm x 25cm.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "A252530F",
    orden: 25,
    categoria: "accesorio",
    tipoAccesorio: "acuario",
    nombre: "Acuario 25 x 25 x 30 + filtro",
    estado: "agotado",
    precio: 33,
    precioAnterior: null,
    descripcion: "Acuario 25cm x 25cm x 30cm + filtro de 5W.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "A252530",
    orden: 26,
    categoria: "accesorio",
    tipoAccesorio: "acuario",
    nombre: "Acuario 25 x 25 x 30",
    estado: "agotado",
    precio: 24,
    precioAnterior: null,
    descripcion: "Acuario 25cm x 25cm x 30cm.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "A303035F",
    orden: 27,
    categoria: "accesorio",
    tipoAccesorio: "acuario",
    nombre: "Acuario 30 x 30 x 35 + filtro",
    estado: "agotado",
    precio: 37,
    precioAnterior: null,
    descripcion: "Acuario 30cm x 30cm x 35cm + filtro de 5W.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "A303035",
    orden: 28,
    categoria: "accesorio",
    tipoAccesorio: "acuario",
    nombre: "Acuario 30 x 30 x 35",
    estado: "agotado",
    precio: 28,
    precioAnterior: null,
    descripcion: "Acuario 30cm x 30cm x 35cm.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "A5wF",
    orden: 29,
    categoria: "accesorio",
    tipoAccesorio: "filtro",
    nombre: "Filtro de 5W",
    estado: "agotado",
    precio: 12,
    precioAnterior: null,
    descripcion: "Filtro de 5W.",
    videoLocal: "",
    videoTikTok: "",
  },
  {
    codigo: "A8wF",
    orden: 30,
    categoria: "accesorio",
    tipoAccesorio: "filtro",
    nombre: "Filtro de 8W",
    estado: "agotado",
    precio: 15,
    precioAnterior: null,
    descripcion: "Filtro de 8W.",
    videoLocal: "",
    videoTikTok: "",
  },*/
];
